{{- if or .Values.sftp.hostKeys.ed25519.key .Values.sftp.hostKeys.rsa.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sftp.hostKeys.ed25519.key }}
  ssh_host_ed25519_key: {{ .Values.sftp.hostKeys.ed25519.key | b64enc }}
  {{- end }}
  {{- if .Values.sftp.hostKeys.rsa.key }}
  ssh_host_rsa_key: {{ .Values.sftp.hostKeys.rsa.key | b64enc }}
  {{- end }}
{{- end }}
