name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

jobs:
  gomod:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            tools/go.sum
      - name: Run go mod tidy
        run: |
          cd tools
          go mod tidy
          git diff --exit-code
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            tools/go.sum
      - name: Perform Chart tests
        run: |
          make tests
          git diff --exit-code
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            tools/go.sum
      - name: Generate Docs
        run: |
          make helm-docs
          git diff --exit-code
